language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration app/phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml