language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.0
before_script:
  - composer install
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover