language: php

env:
  - PHP = "5.6"
  - PHP = "7.0"

php:
  - '5.6'
  - '7.0'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require ${PHP}
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration app/phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
