imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }

framework:
  #esi:             ~
  translator:      { fallback: '%locale%' }
  secret:          '%secret%'
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: '%kernel.debug%'
  form:
    csrf_protection: false
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
    #assets_version: SomeVersionScheme
  default_locale:  '%locale%'
  trusted_proxies: ~
  session:         false
  fragments:       ~

# Twig Configuration
twig:
  debug:            '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
  debug:          '%kernel.debug%'
  use_controller: false
  bundles:        [ ]
  filters:
    cssrewrite: ~
    #closure:
    #    jar: %kernel.root_dir%/Resources/java/compiler.jar
    #yui_css:
    #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: sqlite
    connections:
      sqlite:
        driver:  '%database_driver%'
        host:     '%database_host%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        memory:  false
        path:    '%kernel.root_dir%/prod.db3'


  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: sqlite
        mappings:
          AppBundle: ~

fos_rest:
  param_fetcher_listener: true
  body_converter:
    enabled: false
  serializer:
    serialize_null: true
  routing_loader:
    default_format: json
  view:
    view_response_listener: 'force'
    mime_types:
      json: application/hal+json
      xml: application/hal+xml
    formats:
      json: true
      xml: true

fos_http_cache:
  cache_control:
    rules:
      # the controls section values are used in a call to Response::setCache();
      -
        match:
          path: ^/
          methods: [GET, HEAD]
        headers:
          cache_control: { public: true, max_age: 15, s_maxage: 30 }
          last_modified: '-1 hour'
          vary: [Accept-Encoding, Accept-Language]

hautelook_alice:
  db_drivers:
    orm: ~          # Enable Doctrine ORM if is registered
  seed: 1