imports:
  - { resource: config_dev.yml }

doctrine:
  dbal:
    connections:
      sqlite:
        path:    "%kernel.root_dir%/sqlite.db.cache"

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
  profiler:
    enabled: false

web_profiler:
  toolbar: false
  intercept_redirects: false
